name: CI Lists Updates

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #  branches: [ "main" ]
  schedule:
    - cron: '0 22 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run one URL ipextractor example (Spamhaus block list)
        run: python3 ipexdbl_simple.py 
        
      # Upload extracted IP's
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
        # Artifact name
          name: ipexdbl_simple.txt
        # A file, directory or wildcard pattern that describes what to upload
          path: ipexdbl_simple.txt
        # Retention period
          retention-days: 3  
        # The desired behavior if no files are found using the provided path.
        # Available Options:
        #   warn: Output a warning but do not fail the action
        #   error: Fail the action with an error message
        #   ignore: Do not output any warnings or errors, the action does not fail
        # Optional. Default is 'warn'
          if-no-files-found: error 

      # Runs a set of commands using the runners shell
      - name: Run mutli URL ipextractor example
        run: python3 ipexdbl.py
          echo Run finished
          
      # Upload extracted IP's
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
      # Artifact name
          name: ipexdbl.txt
      # A file, directory or wildcard pattern that describes what to upload
          path: ipexdbl.txt
      # Retention days
          retention-days: 3  
      # Optional. Default is 'warn'
          if-no-files-found: error 

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5      
        with:
      # Optional. Commit message for the created commit.
      # Defaults to "Apply automatic changes"
          commit_message: GitHub Action Automated Change

      # Optional glob pattern of files which should be added to the commit
      # Defaults to all (.)
      # See the `pathspec`-documentation for git
      # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
      # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: '*.txt'

      # Optional. Local file path to the repository.
      # Defaults to the root of the repository.
          repository: .
      
